### ISSUE TITLE
`th04_marisa4_crash_warp` branch actually contains the 'still' code

### ISSUE THREAD

**Issue by wyatt8740** [nmlgc/ReC98#11]
The `th04_marisa4_crash_warp` branch's code is looks to be identical to the code in the `th04_marisa4_crash_still` one. 

    $ git checkout th04_marisa4_crash_warp 
    $ git log|head
    commit 96ca88f6299629973165ed0d7b5a82dc8e26b71d
    Author: nmlgc <nmlgc@nmlgc.net>
    Date:   Fri Apr 15 03:06:49 2022 +0200

        [Mod] [th04] Stage 4 Marisa: Replace the Divide Error with no movement at all
    ...

    $ git log|head
    commit 79a78cac7448ab7f8ce178387c493f61783cdf51
    Author: nmlgc <nmlgc@nmlgc.net>
    Date:   Fri Apr 15 03:06:49 2022 +0200

        [Mod] [th04] Stage 4 Marisa: Replace the Divide Error with no movement at all
        ...

I found this while trying to find if there would be a way to patch my English translated binary in a hex editor to avoid having to try setting up a cross compilation/assembly environment in Linux. I do not have windows on anything at all. I already successfully did this for the EMS crash (for the RHDN patches: change `204E` to `1A4F` at address `0xBD10`).

I did this because I don't think the community fixes are in English.

**Comment by nmlgc** [comment]
Thanks for the report! Fortunately, I still had my 2022 code for both warp variants lying around. They're now on the branch, and I also used the occasion to merge the current `master` into all of these bugfix branches.

Also, here are some [xdelta3 patches for all these TH04 ZUN bug workaround patches](https://github.com/nmlgc/ReC98/files/14053060/th04_zun_bug_workaround_patches.zip).
