### ISSUE TITLE
PoDD remake!

### ISSUE THREAD

**Issue by MIKOsan** [nmlgc/ReC98#3]
I'm doing a remake of PoDD with ReC98 (when I actually get to doing it) and I need help! I need someone who can draw in the PC-98 style, composers who can make PMD music, and people who can make more stages and cutscenes for the game. I'm writing the dialogue and music comments, as well as translating stuff. Here's a TV Tropes darth wiki page on what's gonna go on in the game: http://tvtropes.org/pmwiki/pmwiki.php/DarthWiki/PhantasmagoriaOfDimDreamRemake

**Comment by nmlgc** [comment]
Remakes with fanfiction elements are outside the scope of the core ReC98 project. Feel free to fork this repository and recruit people through your fork's issue tracker, though.

**Comment by MIKOsan** [comment]
ok
